openapi: 3.0.0

info:
  title: Task Manager API
  description: API for managing tasks
  version: 0.0.1

servers:
  - url: http://localhost:8080/api

paths:
  /tasks:
    get:
      summary: Get all tasks
      parameters:
        - name: search
          in: query
          description: Search tasks by title
          required: false
          schema:
            type: string
            example: "Поспать"
        - name: sort
          in: query
          description: Sort tasks by field (created_date, due_date)
          required: false
          schema:
            type: string
            enum: [created_date, due_date]
            default: created_date
            example: created_date
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
        - name: limit
          in: query
          description: Number of tasks per page
          required: false
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                      example: Поспать
                    description:
                      type: string
                      example: Лечь пораньше
                    due_date:
                      type: string
                      example: "2025-05-20 15:00:00"
                    created_date:
                      type: string
                      example: "2025-05-15 12:00:00"
                    status:
                      type: string
                      enum: [Выполнена, Не выполнена]
                    priority:
                      type: string
                      enum: [Низкий, Средний, Высокий]
                    category:
                      type: string
                      example: Личная жизнь
        '400':
          description: Bad request
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Поспать
                description:
                  type: string
                  example: Лечь пораньше
                due_date:
                  type: string
                  example: "2025-05-15 12:00:00"
                status:
                  type: string
                  enum: [Выполнена, Не выполнена]
                priority:
                  type: string
                  enum: [Низкий, Средний, Высокий]
                category:
                  type: string
                  example: Личная жизнь
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  message:
                    type: string
                    example: Task created successfully
        '400':
          description: Bad request
  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          description: task ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    example: Поспать
                  description:
                    type: string
                    example: Лечь пораньше
                  due_date:
                    type: string
                    example: "2025-05-20 15:00:00"
                  created_date:
                    type: string
                    example: "2025-05-15 12:00:00"
                  status:
                    type: string
                    enum: [Выполнена, Не выполнена]
                  priority:
                    type: string
                    enum: [Низкий, Средний, Высокий]
                  category:
                    type: string
                    example: Личная жизнь
        '404':
          description: Task not found
    put:
      summary: Update task by ID
      parameters:
        - name: id
          in: path
          description: task ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Поспать
                description:
                  type: string
                  example: Лечь пораньше
                due_date:
                  type: string
                  example: "2025-05-15 12:00:00"
                status:
                  type: string
                  enum: [Выполнена, Не выполнена]
                priority:
                  type: string
                  enum: [Низкий, Средний, Высокий]
                category:
                  type: string
                  example: Личная жизнь
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task updated successfully
        '400':
          description: Bad request
    delete:
      summary: Delete task by ID
      parameters:
        - name: id
          in: path
          description: task ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task deleted successfully
        '400':
          description: Bad request
